// export const API_BASE_URL = "http://255.255.255.0:9000/api";
// export const ACCESS_TOKEN = "accessToken";

export const ID_MIN_LENGTH = 4;
export const ID_MAX_LENGTH = 16;

export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 15;

export const JOB_GROUP = [
  { value: "JOB_1", label: "웹기획자" },
  { value: "JOB_2", label: "게임기획자" },
  { value: "JOB_3", label: "애니메이션기획자" },
  { value: "JOB_4", label: "컴퓨터하드웨어기술자" },
  { value: "JOB_5", label: "통신공학기술자" },
  { value: "JOB_6", label: "통신기기기술자" },
  { value: "JOB_7", label: "통신망운영기술자" },
  { value: "JOB_8", label: "인공위성개발원" },
  { value: "JOB_9", label: "통신기술개발자" },
  { value: "JOB_10", label: "통신장비기술자" },
  { value: "JOB_11", label: "RFID시스템개발자" },
  { value: "JOB_12", label: "컴퓨터시스템설계분석가" },
  { value: "JOB_13", label: "시스템소프트웨어개발자" },
  { value: "JOB_14", label: "응용소프트웨어개발자" },
  { value: "JOB_15", label: "컴퓨터프로그래머" },
  { value: "JOB_16", label: "디지털영상처리전문가" },
  { value: "JOB_17", label: "가상현실전문가" },
  { value: "JOB_18", label: "음성처리전문가" },
  { value: "JOB_19", label: "게임프로그래머" },
  { value: "JOB_20", label: "모바일콘텐츠개발자" },
  { value: "JOB_21", label: "데이터베이스개발자" },
  { value: "JOB_22", label: "네트워크관리자" },
  { value: "JOB_23", label: "네트워크엔지니어" },
  { value: "JOB_24", label: "컴퓨터보안전문가" },
  { value: "JOB_25", label: "웹엔지니어" },
  { value: "JOB_26", label: "웹프로그래머" },
  { value: "JOB_27", label: "웹마스터" },
  { value: "JOB_28", label: "정보시스템운영자" },
  { value: "JOB_29", label: "방송송출장비기사" },
  { value: "JOB_30", label: "컴퓨터시스템감리전문가" },
  { value: "JOB_31", label: "기술지원전문가" },
  { value: "JOB_32", label: "정보통신컨설턴트" },
  { value: "JOB_33", label: "MIS전문가(경영정보시스템개발자)" },
  { value: "JOB_34", label: "영상및관련장비설치및수리원" },
  { value: "JOB_35", label: "통신및관련장비설치및수리원" },
  { value: "JOB_36", label: "네트워크프로그래머" },
  { value: "JOB_37", label: "통신·방송및인터넷케이블설치및수리원" },
  { value: "JOB_38", label: "웹개발자" },
  { value: "JOB_39", label: "서버개발자" },
  { value: "JOB_40", label: "프론트엔드개발자" },
  { value: "JOB_41", label: "소프트웨어엔지니어" },
  { value: "JOB_42", label: "자바개발자" },
  { value: "JOB_43", label: "안드로이드개발자" },
  { value: "JOB_44", label: "IOS개발자" },
  { value: "JOB_45", label: "Node.js개발자" },
  { value: "JOB_46", label: "데이터엔지니어" },
  { value: "JOB_47", label: "파이썬개발자" },
  { value: "JOB_48", label: "머신러닝엔지니어" },
  { value: "JOB_49", label: "데이터사이언티스트" },
  { value: "JOB_50", label: "빅데이터엔제니어" },
  { value: "JOB_51", label: "QA테스트엔지니어" },
  { value: "JOB_52", label: "기술지원" },
  { value: "JOB_53", label: "개발매니저" },
  { value: "JOB_54", label: "보안엔지니어" },
  { value: "JOB_55", label: "프러닥트매니저" },
  { value: "JOB_56", label: "PHP개발자" },
  { value: "JOB_57", label: "블록체인플랫폼엔지니어" },
  { value: "JOB_58", label: "임베디드개발자" },
  { value: "JOB_59", label: "웹퍼블리셔" },
  { value: "JOB_60", label: "하드웨어엔지니어" },
  { value: "JOB_61", label: "DBA" },
  { value: "JOB_62", label: "크로스플랫폼앱개발자" },
  { value: "JOB_63", label: "영상,음성엔지니어" },
  { value: "JOB_64", label: "그래픽스엔지니어" },
  { value: "JOB_65", label: "CTO,ChiefTechnologyOfficer" },
  { value: "JOB_66", label: "VR엔지니어" },
  { value: "JOB_67", label: "ERP전문가" },
  { value: "JOB_68", label: "루비온레일즈개발자" },
  { value: "JOB_69", label: "CIO,ChiefInformationOfficer" },
  { value: "JOB_70", label: "Fullstack개발자" },
  { value: "JOB_71", label: "프론트앤드개발자" },
  { value: "JOB_72", label: "BL엔지니어" },
  { value: "JOB_73", label: "NET개발자" },
  { value: "JOB_74", label: "영상엔지니어" },
  { value: "JOB_75", label: "음성엔지니어" },
  { value: "JOB_76", label: "시스템,네트워크관리자" },
  { value: "JOB_77", label: "C개발자" },
  { value: "JOB_78", label: "C++개발자" },
  { value: "JOB_79", label: "C#개발자" },
  { value: "JOB_80", label: "빅데이터엔지니어" },
  { value: "JOB_81", label: "블록체인엔지니어" },
  { value: "JOB_82", label: "게임개발자" },
  { value: "JOB_83", label: "DevOps" },
  { value: "JOB_84", label: "프로덕트매니저" },
  { value: "JOB_85", label: "정보보안전문가" },
  { value: "JOB_86", label: "모바일앱개발자" },
  { value: "JOB_87", label: "경영정보시스템(MIS)개발자" },
  { value: "JOB_88", label: "빅데이터분석가" },
  { value: "JOB_89", label: "컴퓨터시스템설계사" },
  { value: "JOB_90", label: "컴퓨터시스템분석가" },
  { value: "JOB_91", label: "웹운영자" },
  { value: "JOB_92", label: "IT기술지원전문가" },
  { value: "JOB_93", label: "정보통신감리원" },
  { value: "JOB_94", label: "서버엔지니어" },
  { value: "JOB_95", label: "화이트해커" },
  { value: "JOB_96", label: "리눅스전문가" },
  { value: "JOB_97", label: "IP전문가" },
  { value: "JOB_98", label: "머신러닝개발자" },
  { value: "JOB_99", label: "정보검색사" },
  { value: "JOB_100", label: "CAD/CAM전문가" },
  { value: "JOB_101", label: "정보시스템감사사" },
  { value: "JOB_102", label: "UX및UI전문가" },
  { value: "JOB_103", label: "악성코드분석가" },
  { value: "JOB_104", label: "리버스엔지니어" },
];

export const USER_TYPE = Object.freeze({
  DEVELOPER: "Developer",
  HEADHUNTER: "headhunter",
});

export const USER_TYPE_SELECT = [
  { value: "Developer", label: "개발자" },
  { value: "headhunter", label: "헤드헌터" },
];

export const TITLE_TAB = Object.freeze({
  NOT: "Not",
  MAIN: "Main",
  JOB: "Job",
});
