// export const API_BASE_URL = "http://255.255.255.0:9000/api";
// export const ACCESS_TOKEN = "accessToken";

export const ID_MIN_LENGTH = 4;
export const ID_MAX_LENGTH = 16;

export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 15;

export const JOB_GROUP = [
  { value: "JOB_1", label: "웹기획자" },
  { value: "JOB_2", label: "게임기획자" },
  { value: "JOB_3", label: "애니메이션기획자" },
  { value: "JOB_4", label: "컴퓨터하드웨어기술자" },
  { value: "JOB_5", label: "통신공학기술자" },
  { value: "JOB_6", label: "통신기기기술자" },
  { value: "JOB_7", label: "통신망운영기술자" },
  { value: "JOB_8", label: "인공위성개발원" },
  { value: "JOB_9", label: "통신기술개발자" },
  { value: "JOB_10", label: "통신장비기술자" },
  { value: "JOB_11", label: "RFID시스템개발자" },
  { value: "JOB_12", label: "컴퓨터시스템설계분석가" },
  { value: "JOB_13", label: "시스템소프트웨어개발자" },
  { value: "JOB_14", label: "응용소프트웨어개발자" },
  { value: "JOB_15", label: "컴퓨터프로그래머" },
  { value: "JOB_16", label: "디지털영상처리전문가" },
  { value: "JOB_17", label: "가상현실전문가" },
  { value: "JOB_18", label: "음성처리전문가" },
  { value: "JOB_19", label: "게임프로그래머" },
  { value: "JOB_20", label: "모바일콘텐츠개발자" },
  { value: "JOB_21", label: "데이터베이스개발자" },
  { value: "JOB_22", label: "네트워크관리자" },
  { value: "JOB_23", label: "네트워크엔지니어" },
  { value: "JOB_24", label: "컴퓨터보안전문가" },
  { value: "JOB_25", label: "웹엔지니어" },
  { value: "JOB_26", label: "웹프로그래머" },
  { value: "JOB_27", label: "웹마스터" },
  { value: "JOB_28", label: "정보시스템운영자" },
  { value: "JOB_29", label: "방송송출장비기사" },
  { value: "JOB_30", label: "컴퓨터시스템감리전문가" },
  { value: "JOB_31", label: "기술지원전문가" },
  { value: "JOB_32", label: "정보통신컨설턴트" },
  { value: "JOB_33", label: "MIS전문가(경영정보시스템개발자)" },
  { value: "JOB_34", label: "영상및관련장비설치및수리원" },
  { value: "JOB_35", label: "통신및관련장비설치및수리원" },
  { value: "JOB_36", label: "네트워크프로그래머" },
  { value: "JOB_37", label: "통신·방송및인터넷케이블설치및수리원" },
  { value: "JOB_38", label: "웹개발자" },
  { value: "JOB_39", label: "서버개발자" },
  { value: "JOB_40", label: "프론트엔드개발자" },
  { value: "JOB_41", label: "소프트웨어엔지니어" },
  { value: "JOB_42", label: "자바개발자" },
  { value: "JOB_43", label: "안드로이드개발자" },
  { value: "JOB_44", label: "IOS개발자" },
  { value: "JOB_45", label: "Node.js개발자" },
  { value: "JOB_46", label: "데이터엔지니어" },
  { value: "JOB_47", label: "파이썬개발자" },
  { value: "JOB_48", label: "머신러닝엔지니어" },
  { value: "JOB_49", label: "데이터사이언티스트" },
  { value: "JOB_50", label: "빅데이터엔제니어" },
  { value: "JOB_51", label: "QA테스트엔지니어" },
  { value: "JOB_52", label: "기술지원" },
  { value: "JOB_53", label: "개발매니저" },
  { value: "JOB_54", label: "보안엔지니어" },
  { value: "JOB_55", label: "프러닥트매니저" },
  { value: "JOB_56", label: "PHP개발자" },
  { value: "JOB_57", label: "블록체인플랫폼엔지니어" },
  { value: "JOB_58", label: "임베디드개발자" },
  { value: "JOB_59", label: "웹퍼블리셔" },
  { value: "JOB_60", label: "하드웨어엔지니어" },
  { value: "JOB_61", label: "DBA" },
  { value: "JOB_62", label: "크로스플랫폼앱개발자" },
  { value: "JOB_63", label: "영상,음성엔지니어" },
  { value: "JOB_64", label: "그래픽스엔지니어" },
  { value: "JOB_65", label: "CTO,ChiefTechnologyOfficer" },
  { value: "JOB_66", label: "VR엔지니어" },
  { value: "JOB_67", label: "ERP전문가" },
  { value: "JOB_68", label: "루비온레일즈개발자" },
  { value: "JOB_69", label: "CIO,ChiefInformationOfficer" },
  { value: "JOB_70", label: "Fullstack개발자" },
  { value: "JOB_71", label: "프론트앤드개발자" },
  { value: "JOB_72", label: "BL엔지니어" },
  { value: "JOB_73", label: "NET개발자" },
  { value: "JOB_74", label: "영상엔지니어" },
  { value: "JOB_75", label: "음성엔지니어" },
  { value: "JOB_76", label: "시스템,네트워크관리자" },
  { value: "JOB_77", label: "C개발자" },
  { value: "JOB_78", label: "C++개발자" },
  { value: "JOB_79", label: "C#개발자" },
  { value: "JOB_80", label: "빅데이터엔지니어" },
  { value: "JOB_81", label: "블록체인엔지니어" },
  { value: "JOB_82", label: "게임개발자" },
  { value: "JOB_83", label: "DevOps" },
  { value: "JOB_84", label: "프로덕트매니저" },
  { value: "JOB_85", label: "정보보안전문가" },
  { value: "JOB_86", label: "모바일앱개발자" },
  { value: "JOB_87", label: "경영정보시스템(MIS)개발자" },
  { value: "JOB_88", label: "빅데이터분석가" },
  { value: "JOB_89", label: "컴퓨터시스템설계사" },
  { value: "JOB_90", label: "컴퓨터시스템분석가" },
  { value: "JOB_91", label: "웹운영자" },
  { value: "JOB_92", label: "IT기술지원전문가" },
  { value: "JOB_93", label: "정보통신감리원" },
  { value: "JOB_94", label: "서버엔지니어" },
  { value: "JOB_95", label: "화이트해커" },
  { value: "JOB_96", label: "리눅스전문가" },
  { value: "JOB_97", label: "IP전문가" },
  { value: "JOB_98", label: "머신러닝개발자" },
  { value: "JOB_99", label: "정보검색사" },
  { value: "JOB_100", label: "CAD/CAM전문가" },
  { value: "JOB_101", label: "정보시스템감사사" },
  { value: "JOB_102", label: "UX및UI전문가" },
  { value: "JOB_103", label: "악성코드분석가" },
  { value: "JOB_104", label: "리버스엔지니어" },
];

export const USER_TYPE = Object.freeze({
  DEVELOPER: 0,
  HEADHUNTER: 1,
  ADMIN: 2,
});

export const USER_TYPE_SELECT = [
  { value: 0, label: "개발자" },
  { value: 1, label: "헤드헌터" },
];

export const CAREER_TYPE_SELECT = [
  { value: 0, label: "경력무관" },
  { value: 1, label: "인턴" },
  { value: 2, label: "신입" },
  { value: 3, label: "경력" },
];

export const TITLE_TAB = Object.freeze({
  NOT: "Not",
  MAIN: "Main",
  JOB: "Job",
  JOB_MANAGEMENT: "JobManagement",
});

export const Location: { [key: string]: string[] } = {
  서울특별시: [
    "강남구",
    "강동구",
    "강북구",
    "강서구",
    "관악구",
    "광진구",
    "구로구",
    "금천구",
    "노원구",
    "도봉구",
    "동대문구",
    "동작구",
    "마포구",
    "서대문구",
    "서초구",
    "성동구",
    "성북구",
    "송파구",
    "양천구",
    "영등포구",
    "용산구",
    "은평구",
    "종로구",
    "중구",
    "중랑구",
  ],
  인천광역시: ["계양구", "남동구", "동구", "미추홀구", "부평구", "서구", "연수구", "중구"],
  부산광역시: ["강서구", "금정구", "남구", "동구", "동래구", "부산진구", "북구", "사상구", "사하구", "서구", "수영구", "연제구", "영도구", "중구", "해운대구"],
  대전광역시: ["대덕구", "동구", "서구", "유성구", "중구"],
  대구광역시: ["남구", "달서구", "달서군", "동구", "북구", "서구", "수성구", "중구"],
  울산광역시: ["남구", "동구", "북구", "중구", "울주군"],
  광주광역시: ["광산구", "남구", "동구", "북구", "서구"],
  제주특별자치도: ["서귀포시", "제주시"],
  세종특별자치시: ["세종특별자치시"],
  경기도: [
    "고양시",
    "과천시",
    "광명시",
    "광주시",
    "구리시",
    "군포시",
    "김포시",
    "남양주시",
    "동두천시",
    "부천시",
    "성남시",
    "수원시",
    "시흥시",
    "안산시",
    "안성시",
    "안양시",
    "양주시",
    "여주시",
    "오산시",
    "용인시",
    "의왕시",
    "의정부시",
    "이천시",
    "파주시",
    "평택시",
    "포천시",
    "하남시",
    "화성시",
    "가평군",
    "양평군",
    "연천군",
  ],
  강원도: [
    "강릉시",
    "동해시",
    "삼척시",
    "속초시",
    "원주시",
    "춘천시",
    "태백시",
    "고성군",
    "양구군",
    "양양군",
    "영월군",
    "인제군",
    "정선군",
    "철원군",
    "평창군",
    "홍천군",
    "화천군",
    "횡성군",
  ],
  충청북도: ["제천시", "청주시", "충주시", "괴산군", "단양군", "보은군", "영동군", "옥천군", "음성군", "증평군", "진천군"],
  충청남도: [
    "계룡시",
    "공주시",
    "논산시",
    "당진시",
    "보령시",
    "서산시",
    "아산시",
    "천안시",
    "금산군",
    "부여군",
    "서천군",
    "예산군",
    "청양군",
    "태안군",
    "홍성군",
  ],
  경상북도: [
    "경산시",
    "경주시",
    "구미시",
    "김천시",
    "문경시",
    "상주시",
    "안동시",
    "영주시",
    "영천시",
    "포항시",
    "고령군",
    "군위군",
    "봉화군",
    "성주군",
    "영덕군",
    "영양군",
    "예천군",
    "울릉군",
    "울진군",
    "의성군",
    "청도군",
    "청송군",
    "칠곡군",
  ],
  경상남도: [
    "거제시",
    "김해시",
    "밀양시",
    "사천시",
    "양산시",
    "진주시",
    "창원시",
    "통영시",
    "거창군",
    "고성군",
    "남해군",
    "산청군",
    "의령군",
    "창녕군",
    "하동군",
    "함안군",
    "함양군",
    "합천군",
  ],
  전라북도: ["군산시", "김제시", "남원시", "익산시", "전주시", "정읍시", "고창군", "무주군", "부안군", "순창군", "완주군", "임실군", "장수군", "진안군"],
  전라남도: [
    "광양시",
    "나주시",
    "목포시",
    "순천시",
    "여수시",
    "강진군",
    "고흥군",
    "곡성군",
    "구례군",
    "담양군",
    "무안군",
    "보성군",
    "신안군",
    "영광군",
    "영암군",
    "완도군",
    "장성군",
    "장흥군",
    "진도군",
    "함평군",
    "해남군",
    "화순군",
  ],
};
